modLoader="javafml" #mandatory
license="All rights reserved"
[[mods]] #mandatory
# The modid of the mod
modId="pearlarmor" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Pearl Armir mod" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
displayURL="https://brandonbr1.github.io" #optional
logoFile="examplemod.png"
credits="" #optional
# A text field displayed in the mod UI
authors="Brandon/jerios" #optional
description='''
A mod that adds pearl armor, swords, ores and clams to get it from
'''
[[dependencies.pearlarmor]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[36,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.pearlarmor]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"